CC = g++
CFLAGS = -Wall -Werror -Wshadow -Wstrict-aliasing -Wstrict-overflow -pedantic
S = ./source/
ALL = $(S)constructor_destructor.cpp $(S)master.cpp
constructor_destructor: $(ALL)
	$(CC) $(CFLAGS) $(ALL) -o constructor_destructor
