CC = g++
CFLAGS = -Wall -Wextra -Werror -Wshadow -Wstrict-aliasing -Wstrict-overflow -pedantic
makefile_exmaple: ./source/makefile_example.cpp ./source/master.cpp
	$(CC) $(CFLAGS) ./source/makefile_example.cpp ./source/master.cpp -o makefile_example
